### ISSUE TITLE
Foiling of cards

### ISSUE THREAD

**Issue by kodawah** [LorcanaJSON/LorcanaJSON#11]
Is there any plans to add more information on whether a card has different foiling?
For example an array listing `{"nonfoil", "coldfoil"}` to indicate the card is available both as non foil and as a cold foil.

This would allow for expansion for future foiling types and would let users describe the cards with more granularity (esp in case there are cards which are only nonfoil or only cold foil.

**Comment by Didero** [comment]
I didn't have any direct plans to add a field like that, but it doesn't sound like too much work to add, since in the input data some cards (like promos) have a 'foil_type' field, with values like 'Lava' or 'Silver', which I could use for this field. For cards without that field, I'll just have to assume they can have either no foiling or cold folding, like you suggested.
I'll add this new 'foilTypes' field in the next release.
Thanks for the suggestion!

**Comment by Didero** [comment]
I've just released a new version of the dataset. It includes some big changes, but also the new 'foilTypes' field you requested. Hopefully it's useful to you!

**Comment by kodawah** [comment]
sweet, thank you
