### ISSUE TITLE
Shimmering Skies

### ISSUE THREAD

**Issue by JSmurf** [LorcanaJSON/LorcanaJSON#12]
It's me again! 

I've been obsessively checking the API for photos of set 5 cards, and it looks like all the Shimmering Skies cards are on the API! 

Hoping it's a smooth update this time! I still need to update my app for the new data formatting.

**Comment by Didero** [comment]
Yeah, I had been checking for the set 5 release every few hours since the start of the week too :D
I've been verifying the cards since Wednesday (local) evening. It's going decently quickly, though I know the Enchanted cards and especially the promo cards they added might pose an issue.
But I'm pretty confident that I can get at least the English datafile update out this weekend at the latest. The French update will come a few days after that.

And hopefully adapting to the V2 format changes will go smoothly for you!

**Comment by Didero** [comment]
I've just published a new version of the LorcanaJSON dataset with all the Set 5 cards, plus some extra promo and special cards, and a few tiny changes. As usual the details are in the [changelog](https://lorcanajson.org/changelog.html#v2024-08-10-2.0.0-1).
I hope they don't keep adding new card designs, if they didn't I would've been done a day ago :p
