### ISSUE TITLE
Making card.Number unique for the same card in the same set

### ISSUE THREAD

**Issue by kodawah** [LorcanaJSON/LorcanaJSON#13]
Hello hello!

I was able to move forward with my app, but then I ran into a bit of a problem with this card: `Dalmatian Puppy - Tail Wagger`

Apparently there are 5 different versions of the same card, but the number remains the same, `4`.
Would it be possible to make it so that number is actually unique, and use the one printing on the card, ie 4a 4b 4c..?

If we don't want to break compatibility because `number` is an integer, what about introducing a string `unique_number` or similar?

Thanks!

**Comment by kodawah** [comment]
btw I am aware of the `fullIdentifier` presence, but I think it'd be much simpler if devs didn't have to manu manipulate that string and could use the main information there!

**Comment by Didero** [comment]
Yeah, that Tail Wagger was a bit of a problem.
When those cards got released, I added two fields to the dataset: 'variant' and 'variantIds'. The `variant` field contains the letter part of the variant, so 'a', 'b', etc., and `variantIds` contains the IDs of the other cards with the same number but a different `variant`.
Combining the `number` and `variant` should hopefully help you here.
So far they've only done this for the 'Tail Wagger' cards, but it'll work the same if they ever make multiple variants for any new cards.

Also, since the 'number' field is set to the first part of the full identifier, there are also promo cards with the same number and setcode as non-promo cards (See for instance 'Ariel - On Human Legs' (ID 1) and 'Mickey Mouse - Brave Little Tailor' (ID 659), both number 1 with `setCode` 1), so the 'number' field isn't unique. In general, the only field that's guaranteed to be unique for each card is the 'id' field, as that field is specifically meant to distinguish cards.

Does this answer help with your problem?

**Comment by kodawah** [comment]
oh I missed the `variant` field, that indeed does work and can help making identifying other cards! I think it'd still be better to have a single field tho, but I understand not wanting to break compatibility (and that's why I was suggesting a new field)

Sorry I wasn't clear with my uniqueness suggestion, I'm aware there are repeated numbers within the same set, I meant to say that card numbers should be unique within the combination of `fullName`+`setCode`+`(collector_)number`. It might be useful being able to recreate a "sort-of" identifier using a this combination, but if you prefer to keep things as they are, it's fine too

thanks a lot for the `variant` tip!

**Comment by Didero** [comment]
Inbetween working on the French data update and my day job, I've been thinking this over. All three of those took more time than I thought, so sorry for the late reply.
I think that with the `id` and the `fullIdentifier` fields, there are already enough fields to distinguish different cards with the same `fullName`. I could add parts of the `fullIdentifier` as separate fields, but that would be duplicate data for most cards, so it'd be rather wasteful.
So I'm not going to add a new field for this. Hopefully that's not too disappointing an answer!
