### ISSUE TITLE
Championship Stitch Promo

### ISSUE THREAD

**Issue by JSmurf** [LorcanaJSON/LorcanaJSON#3]
Hi there! It's me again! 

Just wanted to let you know that the official app has added the new Stitch promo for the Set Championship. 

It seems like now that there are actually adding promos to the app, they might be adding individual promos more regularly. Hopefully this will make it easier to keep our content up-to-date, as long as they don't keep introducing drastically different card types.

**Comment by Didero** [comment]
I meant to reply yesterday, but I kept getting distracted, sorry.
Thanks for the heads-up.
This card causes two problems:
1) It's a promo card but it's listed as rarity 'Enchanted' (it has both the 'promo' and 'Enchanted' symbols at the bottom too). That goes against my assumption that a card can only be one or the other. Should hopefully not be too hard to fix.
2) This is the second promo card for Stitch - Rock Star. This goes against my assumption that a card can only have one promo maximum. This might require a (backwards incompatible) change: turning the 'promoId' number into a 'promoIds' list. This code change might take a bit longer.
I'm pretty busy today and tomorrow, but I'll try to get a fix out either tomorrow or Thursday evening.

**Comment by Didero** [comment]
I've just released the update that adds the new 'Stitch - Rock Star' card.
Since this is the second promo for that card, I had to change some fields, so it's a breaking format change.
I replaced the 'specialId' field containing one ID number with 'promoIds' which is a list of IDs of all the promo cards for that non-promo card.
The 'nonSpecialId' field is renamed to 'nonPromoId' to match.
I felt that using 'promo' in these names was better than the vague 'special', so if I had to make a breaking format change anyway, might as well use a better name too.

This took a few days between work and thinking this solution out with a tired brain, but hopefully any new promos should be far quicker to add now
