### ISSUE TITLE
New App Version - New API

### ISSUE THREAD

**Issue by kibostudios** [LorcanaJSON/LorcanaJSON#8]
Hello,

They've just launched the new app update. 

It seems that the old endpoint is still working, but now it appears to connect to a new one for the updated catalog.

**Comment by Didero** [comment]
Thanks for informing me!
Not sure how quickly I would've realised that the endpoint changed, so thanks for saving me that time :)

And yeah, it seems they changed the data a bit.
For one, they changed the 'magic_ink_color' field that had a single color name to 'magic_ink_color**s**' with a list of color names (though after a quick glance it seems cards still have a max of one color, so maybe it's something for later? Multi-colored cards in set 5?)
Secondly, the 'set_number' field is gone, replaced with a 'card_sets' field. I'm not sure what that field means, because for instance for 'Ariel - On Human Legs' (ID 1), it lists 'card_sets: [2]', which isn't correct...
At least the 'special_rarity_id' card field and the 'special_rarities' dict give me a clear way to label cards from "Illumineer's Quest"
And finally, I see that the IDs I assumed they'd use for the Set 4 cards were actually used, so card IDs won't have to change

It might take me a few days to update the code with these changes though, because I'll annoyingly be a bit busy with other things, and I'll have to think of a good way to mark the 'Illumineer's Quest' cards.
If I delivered just the v1 to v2 URL change now, the whole thing would break because some expected fields won't exist.

Thanks again for informing me!

**Comment by Didero** [comment]
I've just pushed some changes that switch over to v2 of the card catalog and the subsequent needed fixes.
The results for the Quest cards (from the Deep Trouble game) aren't perfect, and I need to verify them, but at least it produces actual text instead of gibberish now, and nothing crashes.
The code can be a bit more efficient, but I'll work on that and on card corrections over the weekend
